### ISSUE TITLE
Mark deprecated functions as deprecated

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/robot_skills#11]
In head.py, there are duplicated functions, such as: 
amigo.head.cancelGoal / amigo.head.cancel_goal
amigo.head.send_goal / amigo.head.setLookAtGoal
amigo.head.setPanTiltGoal / amigo.head.set_pan_tilt

There might be a similar problem in other skills, so i ask the person who create the old or the new skills to just add a print saying Deprecated. Even if i test them one by one to check which work and which don't, someone else will have to do the same to find out.

**Comment by Rayman** [comment]
Fixed by a263e6f58153c2ecf5d023826ae3df0562a77523
