### ISSUE TITLE
Finish TODO wait_for_setpoint, and change it from boolean to timeout

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/robot_skills#14]
In _setHeadReferenceGoal the part to keep the head in the position of the last goal sent is not finished, therefore even goals with priority 1 are being overtaken by lower priorities after a few seconds.

if wait_for_setpoint:
            print "TODO IMPLEMENT wait for setpoint"

Also Janno proposed to change the wait_for_setpoint (boolean), to timeout (time), where timeout=0 would be equivalent to wait_for_setpoint = False, since it wouldn't lock, and above 0 it would behave as True

**Comment by reinzor** [comment]
Closed by a263e6f58153c2ecf5d023826ae3df0562a77523

**Comment by reinzor** [comment]
​I refactored the skills, robot_smach_states and the challenges; for now
on, the interfaces are as follows:

def reset(self, timeout=0):
def look_at_hand(self, side):
def look_at_standing_person(self, timeout=0):
def look_at_point(self, point_stamped, end_time=0, pan_vel=0.2,
tilt_vel=0.2, timeout=0):
def cancel_goal(self):​

Please ask me if you need extra functionality :)

-Rein
