### ISSUE TITLE
State to ask the user's name

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/robot_skills#15]
Do we have something like this working on the new version?

**Comment by egeerts** [comment]
With state HearOptions or with HearOptionsExtra in human_interation.py in robot smach states it can be implemented. We can have a look at this tomorrow.

**Comment by LoyVanBeek** [comment]
A state specifically can contain a HearOptions{Extra} but do a bunch of stuff out-of-the-box without much parameters

**Comment by LFBFerreira** [comment]
Solved, indeed HearOptionsExtra works well. Check AskPersonName state in challenge person recogniton to get an example

**Comment by LoyVanBeek** [comment]
Can you document HearOptionsExtra thoroughly?

**Comment by LFBFerreira** [comment]
I know what they do "from the outside", but i will add some description. Is there some documenting format that i should be aware for python? otherwise i'll do something simple like "param1 - bla bla bla, param2 - bla bla..."

**Comment by Rayman** [comment]
Copied from https://www.python.org/dev/peps/pep-0257/. You were close!

```py
def complex(real=0.0, imag=0.0):
    """Form a complex number.

    Keyword arguments:
    real -- the real part (default 0.0)
    imag -- the imaginary part (default 0.0)
    """
    if imag == 0.0 and real == 0.0:
        return complex_zero
    ...
```

**Comment by LFBFerreira** [comment]
not 1 dash, but 2 dashes!
![](http://cdn.meme.am/instances/58368634.jpg)
