### ISSUE TITLE
Does this work???

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/robot_skills#17]
In line 43-44 in world_model ED, it is checked whether the center point is a a PointStamped. This is, however, not very convenient if the center point is not specified: it default to (0,0,0) in an empty frame, so the transform will always crash...

**Comment by LoyVanBeek** [comment]
This has always worked. 
The default is an empty Point, which by convention with ED is relative to /map. The check is for PointStamped. If that is the case, the PointStamped is transformed to map and then only the .point-part is used for Ed.

Ed should preferably do the transform internally.

**Comment by jlunenburg** [comment]
Either way, navigating using the ED gui does not seem to work anymore (also checked it on a different computer) and the cause seems related. We can discuss it tonight

**Comment by LoyVanBeek** [comment]
This should be very simple to fix, I'll take a look tonight. I think it has been introduced in my pull merge yesterday.

**Comment by LoyVanBeek** [comment]
Fixed in https://github.com/tue-robotics/robot_smach_states/commit/e5324c2b49ec981dd1d04d3558361e3206a6d36c
