### ISSUE TITLE
Add ED entity flag support

### ISSUE THREAD

**Issue by svddries** [tue-robotics/robot_skills#19]
We can now set and query flags on ED entities. This still has to be implemented in the robot_skills layer. To set a flag, send a JSON request to the 'ed/update' service. It needs the following structure:

{
    "entities": [
        {
            "id": "some_id",
            "flags": [
                { "add": "my_flag1" },
                { "add": "my_flag2" },
                { "remove": "my_flag3" },
                ... etc ...
            ]
        }
    ]
}

The flags can be queried using 'ed/simple_query', which returns a list of EntityInfo messages, each with a 'Flag' attribute (list of strings).

**Comment by reinzor** [comment]
Robot skills interface is implemented; however; this does not work:

{"entities":[{"id" : "workshop", "flags":
[{"add":"apple"},{"add":"pear"}]}]}

providing two add actions at the same time.

@svdries

-Rein
