### ISSUE TITLE
Mockbot should implement wait_for_motion_done

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/robot_skills#22]
`robot_skills.mockbot.Torso` should implement the `wait_for_motion_done` interface. challenge_test doesn't run.

**Comment by LoyVanBeek** [comment]
See https://github.com/tue-robotics/robot_skills/commit/0ecc705126739a8414b1663cc53cdb9eb3c12d2f
But the build fails on something else!

**Comment by Rayman** [comment]
I'll try to fix travis

**Comment by Rayman** [comment]
It was fixed by tue-robotics/tue_manipulation_msgs@4be87d06cae6d25aa39fbf76f027ec74ad523161. See the build: https://travis-ci.org/tue-robotics/robot_skills/builds/94169733
