### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/robot_skills#5]
No longer depends on (nonexistent?) packages
* perception_srvs
* obj_in_gripper
* laser_ppl_detection
* depth_map_to_point_cloud

**Comment by Rayman** [comment]
There are still two challenges that heavily depend on `perception_srvs`. Are we going to rewrite those?
- `challenge_follow_me`
- `challenge_restaurant`

Only `reasoner.py` depends on `obj_in_gripper` and that's deprecated so that dependency will be removed. The other two are more complicated.

**Comment by jlunenburg** [comment]
Follow Me will probably not be in the 2015 Rulebook. The restaurant executive will have to be rewritten to be compatible with ED. Nevertheless, this is work that will be done after the first workshop...

**Comment by jlunenburg** [comment]
Another dependency that can be removed is the amigo_inverse_reachability (won't be used anymore, since this is incorporated in the constraint-based navigation

**Comment by LoyVanBeek** [comment]
This has been done already
